### ISSUE TITLE
Add a Select table drop down field in the Add layer stepper

### ISSUE THREAD

**Issue by sannleen** [hikaya-io/dots-frontend#122]
**Is your feature request related to a problem? Please describe.**
Ability to select a table to be used as the source of data for the data layer

**Acceptance Criteria**
A dropdown box whose options are the tables belonging to user's workspace

```
GIVEN I am a logged in user
AND I navigate to the Data page
AND I click on a table. // Layers drawer is displayed
AND I click on `+ Add New Layer` button // A layer modal (Stepper) is displayed
AND Entered the `Layers Name` 
AND Selected a table using the `Select table` drop-down AND then click `Continue`
THEN selected table should be saved and the `Table Name` section marked as complete
```

**Additional context**
![image](https://user-images.githubusercontent.com/16039248/83559699-b2c34e00-a51d-11ea-93ff-acf21e85e16b.png)
![image](https://user-images.githubusercontent.com/16039248/83559727-bbb41f80-a51d-11ea-8a2e-b0d5c375aac1.png)

**Comment by ninetteadhikari** [comment]
@sannleen shall we delete this issue, since its not relevant anymore?

**Comment by sannleen** [comment]
@ninetteadhikari Lets just close it and remove it from the projects board.
