### ISSUE TITLE
User verification notification

### ISSUE THREAD

**Issue by lupyana** [hikaya-io/dots-frontend#129]
**Is your feature request related to a problem? Please describe.**
Notify the user that they need to verify their account to complete the registration

**Acceptance Criteria**
A clear and concise description of how to ensure the feature request is met.

```
GIVEN I am a new user

AND I try to login, before I verify my account


THEN I to be notified to verify my account
```

**Comment by andrewtpham** [comment]
Hey @lupyana, thanks for taking this on. However, I think we may already have an open issue on this: https://github.com/hikaya-io/dots-frontend/issues/29

**Comment by lupyana** [comment]
> Hey @lupyana, thanks for taking this on. However, I think we may already have an open issue on this: #29

Okay thanks for the heads up
