### ISSUE TITLE
Update incorrect email/password notification banner

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#130]
**Is your feature request related to a problem? Please describe.**
When a user enters in the incorrect email and/or password they should receive an error message in a red banner.

**Acceptance Criteria**

```
GIVEN I am a user attempting to log in

AND I enter in my email/username and password (and it is incorrect)

AND I click on the `Login` button

THEN I expect this danger message appear in a red banner:
```
**Additional context**
![image](https://user-images.githubusercontent.com/4407063/83578587-76045080-a537-11ea-9c78-389e60c0ad8a.png)

**Comment by ninetteadhikari** [comment]
this is a duplicate
