### ISSUE TITLE
When a user confirms email, they are redirected to a missing page (404)

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#151]
**Current behavior**
When a user creates a new account, they receive a email confirmation and when the `confirm email` button is clicked, they are redirected to the app and land on a missing page (404 error):

![image](https://user-images.githubusercontent.com/4407063/84261329-e143b900-ab1b-11ea-927d-b249647854cf.png)

**To Reproduce**
1. Go to dots, register a new account and go to your email
2. In the email, click on `confirm email` button
3. You will be redirected to the app but land on a 404 page

**Expected behavior**
The user expects to land on the create first workspace page.

**Comment by sannleen** [comment]
Fixed:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/16039248/84928450-0fef0000-b0d7-11ea-8593-30dfd6771ac9.png">
