### ISSUE TITLE
Display list of all tables

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#153]
**Is your feature request related to a problem? Please describe.**
User wants to see list of all tables

**Acceptance Criteria**
### Issue 1
```
GIVEN I am a logged in user

AND I have already imported tables in the app

WHEN I click on 'Data' item in the top main nav bar

THEN I expect to see the list of all the tables listed 
- For each table I expect to see information on:
  - Table name
  - Number of rows in the table
  - Table owner name
  - Last edited date
  - Data source
```

**Additional context**
<img width="703" alt="Screen Shot 2020-06-10 at 5 47 09 PM" src="https://user-images.githubusercontent.com/13760198/84291508-7ad39080-ab45-11ea-8a4c-4ae3e311f6ed.png">

**Comment by sannleen** [comment]
Implemented
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/16039248/85448226-24337100-b59f-11ea-86fe-908edf3dfb37.png">
