### ISSUE TITLE
Clicking on 'table' button directs to Table detail view

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#154]
**Is your feature request related to a problem? Please describe.**
When user clicks on table button user wants to see the detail view of the table

**Acceptance Criteria**
```
GIVEN I am a logged in user

AND I have already imported tables in the app

AND I click on 'Data' item in the top main nav bar

AND I see the list of all the tables listed 

WHEN I click on the button 'Table'

THEN I am taken to table view page
```

**Additional context**
<img width="807" alt="Screen Shot 2020-06-10 at 6 12 18 PM" src="https://user-images.githubusercontent.com/13760198/84292100-3ac0dd80-ab46-11ea-965d-e8460c867224.png">

<img width="799" alt="Screen Shot 2020-06-10 at 6 12 40 PM" src="https://user-images.githubusercontent.com/13760198/84292115-3eecfb00-ab46-11ea-86d3-ed3ab64c9bf3.png">

**Comment by sannleen** [comment]
Implemented
