### ISSUE TITLE
Table list: Show 'no table selected' message in layers panel

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#156]
**Is your feature request related to a problem? Please describe.**
User will not see any layers if no table is selected

**Acceptance Criteria**

```
GIVEN I am a logged in user

AND I have already imported tables in the app

AND I click on 'Data' item in the top main nav bar

AND I see the list of all the tables listed 

WHEN I have NOT selected a table

THEN I see the left panel with 'Layers' show 'No table selected'
```

**Additional context**
<img width="775" alt="Screen Shot 2020-06-10 at 6 20 29 PM" src="https://user-images.githubusercontent.com/13760198/84292776-1fa29d80-ab47-11ea-908f-025294541258.png">

**Comment by sannleen** [comment]
@TAnas0 and @ninetteadhikari has this been implemented; the current behavior is that when the data page is displayed the list of layers are also displayed without selecting a table.
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/16039248/85170464-19629e80-b276-11ea-8057-8420248e5a2a.png">

**Comment by sannleen** [comment]
Issue reopened since @TAnas0 informed me that this will be implemented as part of https://github.com/hikaya-io/dots-frontend/issues/193

**Comment by sannleen** [comment]
Implemented 👏 
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/16039248/85461938-a32fa600-b5ad-11ea-9aae-35f12495fbb8.png">
