### ISSUE TITLE
Table settings: fields are blank

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#160]
**Current behavior**
The tableObject seems to return undefined values every so often which causes the fields in the settings drawer to appear as blank.

**To Reproduce**
1. Go to Data section
2. Click on an existing table
3. Click on the 'Settings' button in the details page
4. On the Settings panel the table name, owner, and source data fields are blank

**Expected behavior**
The Settings page for tables have table name, owner, and source data fields auto filled in.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-06-11 at 12 55 55 PM" src="https://user-images.githubusercontent.com/13760198/84377489-f0416e80-abe2-11ea-8dd8-6f520a53d186.png">

**Comment by sannleen** [comment]
Fixed:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/16039248/84923178-8d167700-b0cf-11ea-820d-52feb28a8570.png">
