### ISSUE TITLE
Password reset throwing error

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#181]
**Current behavior**
Requesting password reset is showing error
![image](https://user-images.githubusercontent.com/13760198/84923397-72400480-b0c7-11ea-9676-39fd2acc98f0.png)

**To Reproduce**
1. Go to Login page
2. Click on "Forgot password'
3. Add EXISTING email

**Expected behavior**
- When user adds existing email to the 'Forget password' page, user sees a green confirmation banner alert on the page
- User receives an email with reset password link

**Comment by sannleen** [comment]
Fixed
