### ISSUE TITLE
Populate layers list: link the FE to the BE

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#193]
**Is your feature request related to a problem? Please describe.**
Add logic to populate layers. Currently the UI shell is created in the frontend with dummy data.
https://github.com/hikaya-io/dots-frontend/issues/118

**Acceptance Criteria**
Link the FE to the BE to populate the layers list

```
GIVEN I am a logged in user
AND I have already imported tables in the app
AND I click on 'Data' item in the top main nav bar
AND I see the list of all the tables listed 

WHEN I do not select any tables

THEN The left panel with 'Layers' label shows the list of ALL layers for the selected table

WHEN No layer is present 

THEN Display 'No layer is added'
```

![image](https://user-images.githubusercontent.com/13760198/85199808-a4817a00-b2f2-11ea-902e-db6f1044cbdf.png)

![image](https://user-images.githubusercontent.com/13760198/85199794-8a479c00-b2f2-11ea-81f8-9d2f64b29d86.png)

**Comment by sannleen** [comment]
Implemented 👏 
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/16039248/85461938-a32fa600-b5ad-11ea-9aae-35f12495fbb8.png">

**Comment by sannleen** [comment]
Hi @andrewtpham I had tested this in the preview, that is why I moved it to `Done`, is there something else remaining?

**Comment by andrewtpham** [comment]
> Hi @andrewtpham I had tested this in the preview, that is why I moved it to `Done`, is there something else remaining?

@sannleen  No nothing else. Not sure why I had moved this from done, but I suspect the Kanban automation. Thanks for moving it back to done
