### ISSUE TITLE
Forgot password: add link to go back to login page

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#198]
**Is your feature request related to a problem? Please describe.**
On forgot password page, add a link to go back to login page

**Acceptance Criteria**
```
GIVEN I am on the Forgot password page
AND I realize I came to the page by mistake and want to go back to Log in page
AND I see a link to go back to Login page

WHEN I click on the 'Login' link

THEN I am directed to the login page
```

**Additional context**
![image](https://user-images.githubusercontent.com/13760198/85207423-e0373680-b328-11ea-91b4-34d2f7adffef.png)

**Comment by sannleen** [comment]
Implemented:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/16039248/85447409-3fea4780-b59e-11ea-98e2-f6f013f7f856.png">
