### ISSUE TITLE
Profile: Add Language tab

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#23]
With #22 implemented we introduced a language picker (currently transparent) next to the profile icon and we need to come up with an icon to add here. Also we might want to think about where this is placed in the application itself (if it stays in this position or not). 

@ninetteadhikari on this, we might want to put some time to come up with a wireframe for the main navigation and outline of the app to help aid this.

**Comment by andrewtpham** [comment]
Based on conversations, we have decided the language picker will be placed under the Profile Icon, under a tab called `Language`. Updating issue title to reflect move the language picker to this new place when the profile page is implemented #7

**Comment by sannleen** [comment]
@andrewtpham and @lupyana 
Should the language options be the full name or an abbreviation?
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/16039248/84914975-e62cdd80-b0c4-11ea-9f16-a364e18c677c.png">

**Comment by lupyana** [comment]
@sannleen this feature is still a work in progress, it hasn’t reached its final form

**Comment by lupyana** [comment]
Waiting for the api and point to switch languages, and store the user preferences, also looking for a convenient way of generating available options form the localized language files
