### ISSUE TITLE
'Thank you registration' page

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#28]
**Is your feature request related to a problem? Please describe.**
After completing registration, user is directed to a Thank you page.

**Acceptance Criteria**

GIVEN I am a user who has registered an account

WHEN I clicked on `Register` to complete the registration

THEN I am directed to the `Thank you` page:
![image](https://user-images.githubusercontent.com/60480501/80896995-54a70f00-8cc2-11ea-8d15-2809aa420ea8.png)

AND after 5 seconds I will be automatically re-directed to the Log in page:

AND I will receive a email with a verification link

AND I when I click on it I am directed to the log in page

AND a banner will show that my email is verified:
![image](https://user-images.githubusercontent.com/60480501/80896999-5e307700-8cc2-11ea-849b-0a4dfee2519d.png)

OR if the user attempts to log in but has not verified their email:
![image](https://user-images.githubusercontent.com/60480501/80897003-6b4d6600-8cc2-11ea-9690-35850a6c8238.png)

**Comment by andrewtpham** [comment]
We've updated the styling on the Thank you registration page and added a re-direct to the Login page after 5 seconds. I'm assigning to @ninetteadhikari to see if she can try to implement these changes.
