### ISSUE TITLE
Show message on login page when email is not verified

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#29]
**Is your feature request related to a problem? Please describe.**
Show message on login page when email is not verified

**Acceptance Criteria**
```
GIVEN I am an user who has registered an account

AND I have NOT verified my email

WHEN I go to the Log in page

AND I try to log in

THEN I see a banner message saying 'Please verify your email before logging in'
```
Red banner:
- Text: #E95252
- banner background: #FAD8D8

Wireframe:
![image](https://user-images.githubusercontent.com/4407063/83576861-00968100-a533-11ea-971c-dc95a19c3692.png)

**Comment by sannleen** [comment]
Implemented:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/16039248/84634836-0e68e080-aefb-11ea-94ff-8d223700831e.png">
