### ISSUE TITLE
Reset password page

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#30]
**Is your feature request related to a problem? Please describe.**
On the login page, if the user forgets their password, they can click on a link `Forgot password` and be redirected to reset password page.

**Acceptance Criteria**

GIVEN I am a user on the Login page (not logged in)

AND I forgot my password

AND I click on the link `Forgot password`

THEN I expect to be directed to the `Reset your password` page where I can enter in my email and click on a button called `Send password reset email`.
![image](https://user-images.githubusercontent.com/4407063/81448558-dabdcc80-917e-11ea-9111-275934e6dfa2.png)

AND the following email titled "Reset password" should be sent (see attached zip file)

AND I should be redirected to the main login page with a green success banner with a message "An email has been sent. Please check your email."
![image](https://user-images.githubusercontent.com/4407063/81448595-ead5ac00-917e-11ea-9c3b-ccce868a56b0.png)

Green success banner:
- Text: #2AC27F
- Banner background: #D8F3E7

In addition, we need to add a light grey footer to the registration page with the hikaya logo and a link to the main website: https:hikaya.io

HTML file
[Reset password_Dots.html.zip](https://github.com/hikaya-io/dots-frontend/files/4466432/Reset.password_Dots.html.zip)

**Comment by sannleen** [comment]
Hi @michaelbukachi and @andrewtpham will the footer hilkaya icon be implemented on this ticket?
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/16039248/84916211-7586c080-b0c6-11ea-99b4-8c18130e7bcb.png">

**Comment by michaelbukachi** [comment]
Is it supposed to be on all auth pages?
