### ISSUE TITLE
Refactor register page

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#55]
**Is your feature request related to a problem? Please describe.**
We would like to refactor our registration page to instead of using `el-input`, use the `h-label-input` component. We would like to nicely align the input fields so that the label and the input field are in symmetry on the page.

Current:
![image](https://user-images.githubusercontent.com/4407063/81987379-cc1d5c80-9639-11ea-8f4f-dae271b54384.png)

Expected:
![image](https://user-images.githubusercontent.com/4407063/82092819-3dbcdf80-96fa-11ea-8af8-1948dcf28bc9.png)

**Comment by sannleen** [comment]
@andrewtpham When refactoring this page we can add form field validation to it like when a user name exists
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/16039248/83163381-a309cb00-a113-11ea-9e8d-9119d279a24a.png">

Not sure if we need new designs for that?

**Comment by andrewtpham** [comment]
@sannleen I've moved this to its own issue: https://github.com/hikaya-io/dots-frontend/issues/89

**Comment by andrewtpham** [comment]
> @andrewtpham When refactoring this page we can add form field validation to it like when a user name exists
> <img alt="image" width="1673" src="https://user-images.githubusercontent.com/16039248/83163381-a309cb00-a113-11ea-9e8d-9119d279a24a.png">
> 
> Not sure if we need new designs for that?

@sannleen I've moved this to its own issue: #89
