### ISSUE TITLE
Workspace Settings: Details tab

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#60]
**Acceptance Criteria**
A clear and concise description of how to ensure the feature request is met.

```
GIVEN I am a logged in user

AND I have created a workspace

AND I click on my profile icon

AND I click on the Workspace Settings button

THEN I expect to be directed to the Workspace Settings on the Details tab. See screenshot
```

**Additional context**
_Note to dev:_
This page will be scrollable. The inital height of the screen should at least include up to the location field and save button. The danger zone can be shown as you scroll down.

![image](https://user-images.githubusercontent.com/4407063/81993970-1d801880-9647-11ea-8803-3c4d4572a809.png)

**Comment by lupyana** [comment]
@andrewtpham @ninetteadhikari should the menu on the left always be visible?

**Comment by andrewtpham** [comment]
@lupyana yes it should be available on every page. See the “workspace tab” we built in the UI component library for reference.

**Comment by lupyana** [comment]
Ok. thanks the h-tab component needs a little rework. To fit the use case

**Comment by andrewtpham** [comment]
@lupyana ah sorry, I tried my best but would love your help 🙇

**Comment by lupyana** [comment]
> @lupyana ah sorry, I tried my best but would love your help

Already on it
