### ISSUE TITLE
Profile: Add Profile tab

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#7]
**Acceptance Criteria**
GIVEN I am a logged in user

AND I click on my profile icon in the top-right corner

AND click `Profile`

THEN I should be directed to the profile page as displayed below:

![image](https://user-images.githubusercontent.com/4407063/81993402-d8a7b200-9645-11ea-8fae-df7c8a2d1d12.png)

**Comment by lupyana** [comment]
@michaelbukach have already done this, it seems I forgot to assign myself this ticket, what is the progress with this?

**Comment by lupyana** [comment]
If you have not resolved this please let me know so I can push my updates

**Comment by michaelbukachi** [comment]
A bit of work needs to be done on the library. You can push your changes but we will refactor later.

**Comment by lupyana** [comment]
@michaelbukachi  I agree, I have noted a few issues, I will share them with everyone

**Comment by sannleen** [comment]
Implemented:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/16039248/84915365-5cc9db00-b0c5-11ea-8045-bdc40813c229.png">
