### ISSUE TITLE
First workspace creation is not prompted when a user registers

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#76]
**Current behavior**
Currently when a user creates an account, the first workspace creation page does not appear and users are unable to navigate the app.

**Expected behavior**
This is the page we expect after you log in to the app:
![image](https://user-images.githubusercontent.com/4407063/82754329-73358d00-9dcc-11ea-834a-6777c33b4c4d.png)

**Screenshots**
Here are some of the errors received when they log in and see no data:
![image](https://user-images.githubusercontent.com/4407063/82754351-a37d2b80-9dcc-11ea-86bd-e874e926953a.png)

**Comment by sannleen** [comment]
Implemented: <img width="992" alt="image" src="https://user-images.githubusercontent.com/16039248/84927681-d8cc1f00-b0d5-11ea-847a-243eb0aa707f.png">
