### ISSUE TITLE
Workspace Settings: People tab

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#8]
AS a user when I click on my profile icon
AND I click on `Workspace Settings`
AND I should land on the Workspace Settings > Details tab
THEN I can click on the `People` tab
AND I should see the following screens:

![image](https://user-images.githubusercontent.com/4407063/81994682-aa77a180-9648-11ea-98b6-fa3572c0766f.png)

AND if I click on the Search bar, it should expand like this:
![image](https://user-images.githubusercontent.com/4407063/81994706-bbc0ae00-9648-11ea-8ed3-4abe30456bef.png)

AND when I click on the Filter options, I should see it expand with the following options:
![image](https://user-images.githubusercontent.com/4407063/81994723-c7ac7000-9648-11ea-9dae-03b6e2af8a05.png)

AND when I clear the filter and search I should see the `filter` and `search` fields look like this:
![image](https://user-images.githubusercontent.com/4407063/81994797-f1659700-9648-11ea-8c01-8d5dbce0336b.png)

AND when I click on a user (row will highlight with $background-color) and their user role I should be able to change their role to one of the following options:
![image](https://user-images.githubusercontent.com/4407063/81995099-b3b53e00-9649-11ea-879e-ddbbe1d9abf9.png)

AND if I click on the additional settings icon `...` then I should be able to take these actions:
- Resend invitation (only if user hasn't accepted the invite yet)
- Revoke invitation (only if user hasn't accepted the invite yet)
- Deactivate user (only if the user has accepted invite and registered)
![image](https://user-images.githubusercontent.com/4407063/81995207-f6771600-9649-11ea-804f-8514029b3dc1.png)

**Comment by andrewtpham** [comment]
This card is blocked by BasicTable styling: https://github.com/hikaya-io/vue-ui-components/issues/89

**Comment by lupyana** [comment]
This card needs some improvement to be made to some components in Hikawati

- Table 
- Search
- Filter
