### ISSUE TITLE
Ability to enter email or username including support for no case sensitivity

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#80]
**Is your feature request related to a problem? Please describe.**
Currently we support login using a username but not email. In addition the username is case sensitive.

**Acceptance Criteria**
We would like to support the use of email AND username
AND the ability to enter an email OR username without case sensitivity (`Test@gmail.com` OR `test@gmail.com` AND username=`test` OR username=`Test`)

**Comment by andrewtpham** [comment]
This is now resolved by the BE

**Comment by nasirhjafri** [comment]
@andrewtpham We don't have any such validation on FE. So this is already done. You can login using your email too.

**Comment by andrewtpham** [comment]
Ok interesting, you are right. I'm now able to login on the hosted FE. Thanks for checking @nasirhjafri
