### ISSUE TITLE
Remove transformation script so data remains in snake_case throughout the app

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#82]
**Is your feature request related to a problem? Please describe.**
Currently the BE data in snake_case is being transformed to camelCase to adhere to JavaScript standard in the FE.

Use of either format depends on the team and product need. Since one of the key features of Dots will be data import, which relies on the snake_case naming of the variables, it makes sense to use it through out the app. 

**Acceptance Criteria**
Remove the transformation script so that the data format is in snake_case throughout the app (both BE and FE)

cc: @odenypeter @michaelbukachi @andrewtpham

**Comment by andrewtpham** [comment]
Based on call, let's go ahead and implement this ticket. cc: @michaelbukachi
