### ISSUE TITLE
Workspace Description textbox using a different font family

### ISSUE THREAD

**Issue by sannleen** [hikaya-io/dots-frontend#86]
**Current behavior**
Workspace **Description** field is using `monospace` font-family while other text fields are using `Arial` font family

**To Reproduce**
1. **Workspace Details** page
2. Workspace **Description** field is using `monospace` font-family

**Expected behavior**
All textbox fields should be of the same font-family

**Screenshots**
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/16039248/83165579-67bccb80-a116-11ea-918e-69a701ed6bd2.png">

**Comment by andrewtpham** [comment]
Thanks for flagging this! This will be resolved by PR #123
