### ISSUE TITLE
When you logout and login using a different user, the logged in user is able to access the previous user's workspace

### ISSUE THREAD

**Issue by sannleen** [hikaya-io/dots-frontend#88]
**Current behavior**
When you logout and login using a different user, the logged in user is able to access the previous user's workspace

**To Reproduce**
1. Login using `user 1`
2. Logout `user 1`
3. Login using `user 2`
4. `user 2` sees `user 1` workspace
5. When you refresh the browser `user 2` workspace is now displayed

**Expected behavior**
When a user logs out their workspace should not be accessible by a different user who logs in in the same browser.

**Screenshots**
![workspace_access_issue](https://user-images.githubusercontent.com/16039248/83168003-88d2eb80-a119-11ea-9c40-7d582a07a6a3.gif)

**Comment by andrewtpham** [comment]
@sannleen if you get a chance could you kindly test this and see if it meets your prescribed AC? Thanks!

**Comment by sannleen** [comment]
Hi @TAnas0 it seems the issue is still not fixed; only the workspaces are being cleared
I tested https://github.com/hikaya-io/dots-frontend/pull/114 on https://dots-git-dots-88.hikaya.now.sh

See recording below:
![user_details_reset_issue](https://user-images.githubusercontent.com/16039248/83458693-98309c80-a46b-11ea-95f7-09c908f0a5e8.gif)

**Comment by andrewtpham** [comment]
@TAnas0 to open a 2nd PR to reset the store fully when you log-in/log out
