### ISSUE TITLE
Style Table view

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#96]
**Is your feature request related to a problem? Please describe.**
Add styling to table view page to include:
- [ ] Table name 
- [ ] Back button arrow to go to Table list page
- [ ] Select option per row
- [ ] Sort option for each column
- [ ] Table to fill the right end of the screen and bottom end of the screen
- [ ] Table is scrollable to right and bottom of screen with left and top margins as fixed

**Additional context**
![image](https://user-images.githubusercontent.com/13760198/83751204-c0381f80-a666-11ea-9510-5e7968dbfd36.png)

**Comment by sannleen** [comment]
Fixed
![image](https://user-images.githubusercontent.com/16039248/85171806-65aede00-b278-11ea-806b-98836d2a1547.png)
