### ISSUE TITLE
Add settings button and panel on Table view page

### ISSUE THREAD

**Issue by ninetteadhikari** [hikaya-io/dots-frontend#97]
**Is your feature request related to a problem? Please describe.**
Have a settings page for each table, for options to edit table information and delete table

**Acceptance Criteria**

```
GIVEN I am a logged in user with Admin or Edit role

WHEN I navigate to Tables page and click on 'view table'

AND on the Table view page I click on the 'Settings' button

THEN a left panel will appear with options to edit my 
- Table name
- I see Owner which is non-editable (disabled)
- Location (text field)
- Source (non-editable)

AND I also see buttons to 
- Update or refresh data in the table (#98)
- Export the data table (#100)
- Delete the data table (#99)
Note: separate tickets are there for the above 3 functions
```

**Additional context**
![image](https://user-images.githubusercontent.com/13760198/83752914-a0eec180-a669-11ea-9131-69647132b4dc.png)

**Comment by sannleen** [comment]
Fixed:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/16039248/84925484-a0771180-b0d2-11ea-8efa-f4aa8aa37d47.png">
